### PR TITLE
Add multi-author example

### LINKED ISSUE #2: Multiple authors
It would be nice to extend the template to include multiple authors, some sharing, some not sharing affiliations.

### PR DESCRIPTION
**Pull request by jchodera**
Fixes #2

### CODE REVIEW

**Comment by bas-rustenburg** [comment]
I noticed from working with the template that authors with individual emails but the same affiliation end up in wrong footnotes where only one email is referred to for all those authors. I'm not sure how to fix that exactly..

**Comment by bas-rustenburg** [comment]
The issue appears to be that emails get associated with affiliations, not authors.

**Comment by bas-rustenburg** [comment]
It appears that the fix is putting the emails BEFORE affiliation in the listing of authors.

**Comment by jchodera** [comment]
Can you merge and fix?

**Comment by bas-rustenburg** [comment]
Will add reminder to fix later.

**Pull request merged**
